export type DataSourceMode = "supabase" | "local";

export type Project = {
  id?: string;
  sourceKey: string;
  sourceRow?: number | null;
  groupName?: string | null;
  projectName: string;
  jobNumber?: string | null;
  installationDate?: string | null;
  fixedDate?: string | null;
  drawingsRequiredDate?: string | null;
  mondayStatus?: string | null;
  stage?: string | null;
  calcStatus?: string | null;
  detailingStart?: string | null;
  detailingDaysRemaining?: number | null;
  status?: string | null;
  rep?: string | null;
  ownerDynamics?: string | null;
  detailer?: string | null;
  orderValue?: number | null;
  userFolderPath?: string | null;
  driveFolderPath?: string | null;
  comments?: string | null;
  deliveryComments?: string | null;
  useCase?: string | null;
  exClass?: string | null;
  windSite?: string | null;
  windStructure?: string | null;
  snow?: string | null;
  altitude?: string | null;
  windSnowLoads?: string | null;
  structureType?: string | null;
  style?: string | null;
  roofShape?: string | null;
  supportType?: string | null;
  structureSize?: string | null;
  claddingType?: string | null;
  gableEnds?: string | null;
  sidewalls?: string | null;
  distToSeaK?: number | null;
  frameworkFinish?: string | null;
  colour?: string | null;
  galvHolesAdded?: string | null;
  boltCapColour?: string | null;
  foundationsBy?: string | null;
  concreteType?: string | null;
  padFinish?: string | null;
  createdOn?: string | null;
  siteAccount?: string | null;
  siteAccountIndustry?: string | null;
  sitePostCode?: string | null;
  location?: string | null;
  accAddToLocation?: string | null;
  nearestAe?: string | null;
  billingAccount?: string | null;
  approvalContact?: string | null;
  siteLiaisonContact?: string | null;
  endClientContact?: string | null;
  frameworkInstaller?: string | null;
  groundworker?: string | null;
  padFinisher?: string | null;
  inactiveReason?: string | null;
  invoicedValue?: number | null;
  jobCost?: number | null;
  jobProfit?: number | null;
  jobMargin?: number | null;
  lowMarginReasonDescription?: string | null;
  lowMarginReasonType?: string | null;
  opportunity?: string | null;
  orderConfirmed?: string | null;
  mfgZone?: string | null;
  mfgCantColumn?: string | null;
  itemId?: string | null;
  gwkSupplierConnect?: string | null;
  padFinishQuotes?: string | null;
  newWordDoc?: string | null;
  files?: string | null;
  timeTracking?: string | null;
  pmSelectionList?: string | null;
  mfgOrOther?: string | null;
  pmRequiredItems?: string | null;
  email?: string | null;
  ramsSignOff?: string | null;
  mobilePhone?: string | null;
  rams?: string | null;
};

export type ProjectNote = {
  id: string;
  projectId: string;
  body: string;
  createdBy?: string | null;
  createdAt: string;
};

export type ProjectsPayload = {
  projects: Project[];
  source: DataSourceMode;
  error?: string;
};

